baseurl = "https://www.devean.cn/"
metaDataFormat = "yaml"
theme = "blist"

DefaultContentLanguage = "zh"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.zh]
    title = "Devean 布洛克"
    description = "Devean 的个人博客"
    contentDir="content/zh"
    weight = 1
    languageName = "中文"
    [languages.zh.params]
      introTitle = "路在脚下、心在远方"
      introSubtitle = "如同天地间的流动之歌。踏上旅程，心随风飘，行走在时光的长廊，每一步都是对未知的勇敢探索，每一次呼吸都是对生命的珍视。"
      introPhoto = "/img/bj/ladder-sky-bg.jpg"
      logo = "/favicon.svg"
    [[languages.zh.menu.main]]
        name = "博客"
        url = "blog"
        weight = 1

    [[languages.zh.menu.main]]
        name = "关于"
        url = "page/about/"
        weight = 2

    [[languages.zh.menu.main]]
        name = "标签"
        url = "tags"
        weight = 3
    [[languages.zh.menu.main]]
        name = "AI 知识库"
        url = "https://ai.devean.cn/"
        weight = 4
  [languages.en]
    title = "Devean Medium"
    description = "Devean Personal Blog"
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "The road is under feet, while heart is in the distance"
      introSubtitle = ""
      introPhoto = "/img/bj/ladder-sky-bg.jpg"
      logo = "/favicon.svg"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "AI Know Hub"
        url = "https://ai.devean.cn/en/"
        weight = 4

[params]
   logo= "/favicon.svg"

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Devean©2019-Now"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  # Baidu Analytics
  ba_track_id = "1ae0b78ddcca3b07f0cf346c87ee7585"

  # algolia site search
  algolia_search = true
  algolia_appId = "HSQWDBMC2T"
  algolia_indexName = "DeveanBlog"
  algolia_apiKey = "e6f3dbe435f1b262622db4ca6d2fbebb"


[params.busuanzi]
    enable = false

# Comments system
[params.comments]
  enable=true
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = "devon-ye/devon-ye.github.io"
  repoid = "R_kgDOKsihIw"
  category = "Announcements"
  categoryid = "DIC_kwDOKsihI84CdO_B"
  mapping = "pathname"
  strict = "0"
  reactionsenabled = "1"
  emitmetadata = "0"
  inputposition = "bottom"
  theme = "light"

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = ""
  description = ""

  [[params.homepage.social.icons]]
    website = "email"
    url = "devean.ye@gmail.com"
  [[params.homepage.social.icons]]
    website = "stackoverflow"
    url = "https://stackoverflow.com/users/7220519"
  [[params.homepage.social.icons]]
    website = "processsOn"
    url = "https://www.processon.com/u/593ac0e9e4b0815a28c1f7b4"
#  [[params.homepage.social.icons]]
#    website = "linkedin"
#    url = "https://linkedin.com/in/"
  [[params.homepage.social.icons]]
    website = "wechat"
    url = "img/wechat-QRCode.png"
#  [[params.homepage.social.icons]]
#    website = "telegram"
#    url = "https://t.me/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/devon-ye"
  [[params.homepage.social.icons]]
    website = "zhihu"
    url = "https://www.zhihu.com/people/devonaha"
#  [[params.homepage.social.icons]]
#    website = "buymeacoffee"
#    url = "https://www.buymeacoffee.com/"
#  [[params.homepage.social.icons]]
#    website = "medium"
#    url = "https://medium.com/"
#  [[params.homepage.social.icons]]
#    website = "reddit"
#    url = "https://reddit.com/"
#  [[params.homepage.social.icons]]
#    website = "dribbble"
#    url = "https://dribbble.com/"
#  [[params.homepage.social.icons]]
#    website = "xda"
#    url = "https://forum.xda-developers.com/"
#  [[params.homepage.social.icons]]
#    website = "tiktok"
#    url = "https://tiktok.com"
#  [[params.homepage.social.icons]]
#    website = "googlescholar"
#    url = "https://scholar.google.com/"
#  [[params.homepage.social.icons]]
#    website = "mastodon"
#    url = "https://joinmastodon.org"
#  [[params.homepage.social.icons]]
#    website = "youtube"
#    url = "https://www.youtube.com/@yedevean"
#  [[params.homepage.social.icons]]
#    website = "instagram"
#    url = "https://instagram.com"
#  [[params.homepage.social.icons]]
#    website = "facebook"
#    url = "https://facebook.com"
#  [[params.homepage.social.icons]]
#    website = "behance"
#    url = "https://behance.net"
  [[params.homepage.social.icons]]
    website = "cnblogs"
    url = "https://www.cnblogs.com/Devonmusa"
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
